### ISSUE TITLE
Applying this model on new binary datasets

### ISSUE THREAD

**Issue by angrypiggy** [siplab-gt/Manifold_Autoencoder#1]
Hi Marissa,

Thanks for the excellent work! I am thinking about applying this model on a binary animal mask dataset, in the hope that it can model on complex shape contour of the species and generate realistic samples that are different from the training samples. Do you think it is a feasible application? Thank you so much!

**Comment by mnorko** [comment]
Yuliang,
Thank you for your interest in this work! First, I'm not familiar with the binary animal mask dataset, what does the data look like there? Does the data include just images? Or the mask boundaries? or mask volumes? 

Second, I wanted to point you to an improved implementation of this model for a follow up paper: https://github.com/siplab-gt/manifold-autoencoder-extended The code in this repo trains the same sort of neural network model but more efficiently and robustly.

**Comment by angrypiggy** [comment]
Hi Marissa,

Thank you for the quick reply! I attached a screenshot of some data samples, and they are basically some binary images. I also have the corresponding RGB images too. The desired goal is to learn the contour manifold and generate realistic and new samples. 

Thanks for the link! I have read the three serial papers, and I think they are quite relevant too. 
![Screenshot from 2021-07-20 21-07-59](https://user-images.githubusercontent.com/49012574/126417580-203efded-95f8-4979-88cd-887a855b8c04.png)
